[tox]
requires =
    tox>=4.2
env_list =
    lint
    py{313, 312, 311}

[testenv]
description = run unit tests
skip_install = true
allowlist_externals =
    uv
set_env =
    UV_PROJECT_ENVIRONMENT = {envdir}
commands_pre =
    uv sync --frozen --no-dev --group test --python {envpython}
commands =
    uv run pytest tests/ --import-mode importlib

[testenv:lint]
description = run linters
skip_install = true
deps =
    black>=23
    isort>=5.12
commands_pre =
commands =
    isort --check-only {posargs:.}
    black --check {posargs:.}
