name: lint & test

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v5

      - name: Setup uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          cache-dependency-glob: |
            **/pyproject.toml
            **/uv.lock

      - name: Install dependencies
        run: uv sync --frozen --group test

      - name: Lint with isort
        run: uv run isort --check-only --jobs -1 .

      - name: Lint with black
        run: uv run black --check .

      - name: Run pyright
        uses: jakebailey/pyright-action@v1.6.0

      - name: Run test
        run: uv run pytest tests/ --import-mode importlib
